/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OpenPark - Parking Lot Server
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { mutationInstance } from '../services/api';
export interface EntryResponse {
  event: 'entry';
  entered_at: string;
}

export interface ExitResponse {
  event: 'exit';
  fee: number;
  parked_duration_minutes: number;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LogOut {
  id: string;
  parking_lot_id: string;
  plate: string;
  event_type: string;
  fee: number | null;
  client_timestamp: string;
  server_received_at: string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LotCreate {
  name: string;
  address?: string | null;
  /** @exclusiveMinimum 0 */
  total_spaces: number;
  base_fee?: number;
  base_duration_minutes?: number;
  extra_fee_per_unit?: number;
  /** @exclusiveMinimum 0 */
  extra_fee_unit_minutes?: number;
  daily_max_fee?: number | null;
}

export interface LotOut {
  id: string;
  owner_user_id: string;
  name: string;
  address: string | null;
  total_spaces: number;
  available_spaces: number;
  base_fee: number;
  base_duration_minutes: number;
  extra_fee_per_unit: number;
  extra_fee_unit_minutes: number;
  daily_max_fee: number | null;
  api_key: string;
  created_at: string;
  updated_at: string;
}

export interface LotPatch {
  name?: string | null;
  address?: string | null;
  total_spaces?: number | null;
  base_fee?: number | null;
  base_duration_minutes?: number | null;
  extra_fee_per_unit?: number | null;
  extra_fee_unit_minutes?: number | null;
  daily_max_fee?: number | null;
}

export interface PlateRequest {
  plate: string;
  timestamp: string;
}

export interface SignupRequest {
  username: string;
  email: string;
  password: string;
}

export interface SignupResponse {
  id: string;
  username: string;
  email: string;
  created_at: string;
}

export interface TokenResponse {
  access_token: string;
  token_type?: string;
}

export interface VehicleOut {
  id: string;
  parking_lot_id: string;
  plate: string;
  entered_at: string;
}

export type ListLogsApiV1LotsLotIdLogsGetParams = {
date_from?: string | null;
date_to?: string | null;
plate?: string | null;
event_type?: string | null;
/**
 * @maximum 200
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};

/**
 * @summary Signup
 */
export const signupApiV1SignupPost = (
    signupRequest: SignupRequest,
 signal?: AbortSignal
) => {


      return mutationInstance<SignupResponse>(
      {url: `/api/v1/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest, signal
    },
      );
    }



export const getSignupApiV1SignupPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupApiV1SignupPost>>, TError,{data: SignupRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof signupApiV1SignupPost>>, TError,{data: SignupRequest}, TContext> => {

const mutationKey = ['signupApiV1SignupPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signupApiV1SignupPost>>, {data: SignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  signupApiV1SignupPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SignupApiV1SignupPostMutationResult = NonNullable<Awaited<ReturnType<typeof signupApiV1SignupPost>>>
    export type SignupApiV1SignupPostMutationBody = SignupRequest
    export type SignupApiV1SignupPostMutationError = HTTPValidationError

    /**
 * @summary Signup
 */
export const useSignupApiV1SignupPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupApiV1SignupPost>>, TError,{data: SignupRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signupApiV1SignupPost>>,
        TError,
        {data: SignupRequest},
        TContext
      > => {
      return useMutation(getSignupApiV1SignupPostMutationOptions(options), queryClient);
    }

/**
 * @summary Login
 */
export const loginApiV1LoginPost = (
    loginRequest: LoginRequest,
 signal?: AbortSignal
) => {


      return mutationInstance<TokenResponse>(
      {url: `/api/v1/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      );
    }



export const getLoginApiV1LoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiV1LoginPost>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof loginApiV1LoginPost>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginApiV1LoginPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginApiV1LoginPost>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginApiV1LoginPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginApiV1LoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginApiV1LoginPost>>>
    export type LoginApiV1LoginPostMutationBody = LoginRequest
    export type LoginApiV1LoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginApiV1LoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiV1LoginPost>>, TError,{data: LoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginApiV1LoginPost>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getLoginApiV1LoginPostMutationOptions(options), queryClient);
    }

/**
 * @summary List Lots
 */
export const listLotsApiV1LotsGet = (

 signal?: AbortSignal
) => {


      return mutationInstance<LotOut[]>(
      {url: `/api/v1/lots`, method: 'GET', signal
    },
      );
    }




export const getListLotsApiV1LotsGetQueryKey = () => {
    return [
    `/api/v1/lots`
    ] as const;
    }


export const getListLotsApiV1LotsGetQueryOptions = <TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLotsApiV1LotsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>> = ({ signal }) => listLotsApiV1LotsGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListLotsApiV1LotsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>>
export type ListLotsApiV1LotsGetQueryError = unknown


export function useListLotsApiV1LotsGet<TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLotsApiV1LotsGet>>,
          TError,
          Awaited<ReturnType<typeof listLotsApiV1LotsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLotsApiV1LotsGet<TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLotsApiV1LotsGet>>,
          TError,
          Awaited<ReturnType<typeof listLotsApiV1LotsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLotsApiV1LotsGet<TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Lots
 */

export function useListLotsApiV1LotsGet<TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListLotsApiV1LotsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Create Lot
 */
export const createLotApiV1LotsPost = (
    lotCreate: LotCreate,
 signal?: AbortSignal
) => {


      return mutationInstance<LotOut>(
      {url: `/api/v1/lots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: lotCreate, signal
    },
      );
    }



export const getCreateLotApiV1LotsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLotApiV1LotsPost>>, TError,{data: LotCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLotApiV1LotsPost>>, TError,{data: LotCreate}, TContext> => {

const mutationKey = ['createLotApiV1LotsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLotApiV1LotsPost>>, {data: LotCreate}> = (props) => {
          const {data} = props ?? {};

          return  createLotApiV1LotsPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateLotApiV1LotsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createLotApiV1LotsPost>>>
    export type CreateLotApiV1LotsPostMutationBody = LotCreate
    export type CreateLotApiV1LotsPostMutationError = HTTPValidationError

    /**
 * @summary Create Lot
 */
export const useCreateLotApiV1LotsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLotApiV1LotsPost>>, TError,{data: LotCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLotApiV1LotsPost>>,
        TError,
        {data: LotCreate},
        TContext
      > => {
      return useMutation(getCreateLotApiV1LotsPostMutationOptions(options), queryClient);
    }

/**
 * @summary Get Lot
 */
export const getLotApiV1LotsLotIdGet = (
    lotId: string,
 signal?: AbortSignal
) => {


      return mutationInstance<LotOut>(
      {url: `/api/v1/lots/${lotId}`, method: 'GET', signal
    },
      );
    }




export const getGetLotApiV1LotsLotIdGetQueryKey = (lotId: string,) => {
    return [
    `/api/v1/lots/${lotId}`
    ] as const;
    }


export const getGetLotApiV1LotsLotIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLotApiV1LotsLotIdGetQueryKey(lotId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>> = ({ signal }) => getLotApiV1LotsLotIdGet(lotId, signal);





   return  { queryKey, queryFn, enabled: lotId !== null && lotId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLotApiV1LotsLotIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>>
export type GetLotApiV1LotsLotIdGetQueryError = HTTPValidationError


export function useGetLotApiV1LotsLotIdGet<TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(
 lotId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLotApiV1LotsLotIdGet<TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(
 lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLotApiV1LotsLotIdGet<TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(
 lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Lot
 */

export function useGetLotApiV1LotsLotIdGet<TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(
 lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLotApiV1LotsLotIdGetQueryOptions(lotId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Update Lot
 */
export const updateLotApiV1LotsLotIdPatch = (
    lotId: string,
    lotPatch: LotPatch,
 signal?: AbortSignal
) => {


      return mutationInstance<LotOut>(
      {url: `/api/v1/lots/${lotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: lotPatch, signal
    },
      );
    }



export const getUpdateLotApiV1LotsLotIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLotApiV1LotsLotIdPatch>>, TError,{lotId: string;data: LotPatch}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLotApiV1LotsLotIdPatch>>, TError,{lotId: string;data: LotPatch}, TContext> => {

const mutationKey = ['updateLotApiV1LotsLotIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLotApiV1LotsLotIdPatch>>, {lotId: string;data: LotPatch}> = (props) => {
          const {lotId,data} = props ?? {};

          return  updateLotApiV1LotsLotIdPatch(lotId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLotApiV1LotsLotIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateLotApiV1LotsLotIdPatch>>>
    export type UpdateLotApiV1LotsLotIdPatchMutationBody = LotPatch
    export type UpdateLotApiV1LotsLotIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Lot
 */
export const useUpdateLotApiV1LotsLotIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLotApiV1LotsLotIdPatch>>, TError,{lotId: string;data: LotPatch}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLotApiV1LotsLotIdPatch>>,
        TError,
        {lotId: string;data: LotPatch},
        TContext
      > => {
      return useMutation(getUpdateLotApiV1LotsLotIdPatchMutationOptions(options), queryClient);
    }

/**
 * @summary Delete Lot
 */
export const deleteLotApiV1LotsLotIdDelete = (
    lotId: string,
 signal?: AbortSignal
) => {


      return mutationInstance<void>(
      {url: `/api/v1/lots/${lotId}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteLotApiV1LotsLotIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLotApiV1LotsLotIdDelete>>, TError,{lotId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteLotApiV1LotsLotIdDelete>>, TError,{lotId: string}, TContext> => {

const mutationKey = ['deleteLotApiV1LotsLotIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLotApiV1LotsLotIdDelete>>, {lotId: string}> = (props) => {
          const {lotId} = props ?? {};

          return  deleteLotApiV1LotsLotIdDelete(lotId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLotApiV1LotsLotIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLotApiV1LotsLotIdDelete>>>

    export type DeleteLotApiV1LotsLotIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Lot
 */
export const useDeleteLotApiV1LotsLotIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLotApiV1LotsLotIdDelete>>, TError,{lotId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLotApiV1LotsLotIdDelete>>,
        TError,
        {lotId: string},
        TContext
      > => {
      return useMutation(getDeleteLotApiV1LotsLotIdDeleteMutationOptions(options), queryClient);
    }

/**
 * @summary List Vehicles
 */
export const listVehiclesApiV1LotsLotIdVehiclesGet = (
    lotId: string,
 signal?: AbortSignal
) => {


      return mutationInstance<VehicleOut[]>(
      {url: `/api/v1/lots/${lotId}/vehicles`, method: 'GET', signal
    },
      );
    }




export const getListVehiclesApiV1LotsLotIdVehiclesGetQueryKey = (lotId: string,) => {
    return [
    `/api/v1/lots/${lotId}/vehicles`
    ] as const;
    }


export const getListVehiclesApiV1LotsLotIdVehiclesGetQueryOptions = <TData = Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError = HTTPValidationError>(lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVehiclesApiV1LotsLotIdVehiclesGetQueryKey(lotId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>> = ({ signal }) => listVehiclesApiV1LotsLotIdVehiclesGet(lotId, signal);





   return  { queryKey, queryFn, enabled: lotId !== null && lotId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVehiclesApiV1LotsLotIdVehiclesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>>
export type ListVehiclesApiV1LotsLotIdVehiclesGetQueryError = HTTPValidationError


export function useListVehiclesApiV1LotsLotIdVehiclesGet<TData = Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError = HTTPValidationError>(
 lotId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>,
          TError,
          Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVehiclesApiV1LotsLotIdVehiclesGet<TData = Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError = HTTPValidationError>(
 lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>,
          TError,
          Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVehiclesApiV1LotsLotIdVehiclesGet<TData = Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError = HTTPValidationError>(
 lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Vehicles
 */

export function useListVehiclesApiV1LotsLotIdVehiclesGet<TData = Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError = HTTPValidationError>(
 lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehiclesApiV1LotsLotIdVehiclesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVehiclesApiV1LotsLotIdVehiclesGetQueryOptions(lotId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Force Exit Vehicle
 */
export const forceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete = (
    lotId: string,
    vehicleId: string,
 signal?: AbortSignal
) => {


      return mutationInstance<void>(
      {url: `/api/v1/lots/${lotId}/vehicles/${vehicleId}`, method: 'DELETE', signal
    },
      );
    }



export const getForceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete>>, TError,{lotId: string;vehicleId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof forceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete>>, TError,{lotId: string;vehicleId: string}, TContext> => {

const mutationKey = ['forceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof forceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete>>, {lotId: string;vehicleId: string}> = (props) => {
          const {lotId,vehicleId} = props ?? {};

          return  forceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete(lotId,vehicleId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ForceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof forceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete>>>

    export type ForceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Force Exit Vehicle
 */
export const useForceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete>>, TError,{lotId: string;vehicleId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof forceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDelete>>,
        TError,
        {lotId: string;vehicleId: string},
        TContext
      > => {
      return useMutation(getForceExitVehicleApiV1LotsLotIdVehiclesVehicleIdDeleteMutationOptions(options), queryClient);
    }

/**
 * @summary List Logs
 */
export const listLogsApiV1LotsLotIdLogsGet = (
    lotId: string,
    params?: ListLogsApiV1LotsLotIdLogsGetParams,
 signal?: AbortSignal
) => {


      return mutationInstance<LogOut[]>(
      {url: `/api/v1/lots/${lotId}/logs`, method: 'GET',
        params, signal
    },
      );
    }




export const getListLogsApiV1LotsLotIdLogsGetQueryKey = (lotId: string,
    params?: ListLogsApiV1LotsLotIdLogsGetParams,) => {
    return [
    `/api/v1/lots/${lotId}/logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getListLogsApiV1LotsLotIdLogsGetQueryOptions = <TData = Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError = HTTPValidationError>(lotId: string,
    params?: ListLogsApiV1LotsLotIdLogsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLogsApiV1LotsLotIdLogsGetQueryKey(lotId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>> = ({ signal }) => listLogsApiV1LotsLotIdLogsGet(lotId,params, signal);





   return  { queryKey, queryFn, enabled: lotId !== null && lotId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListLogsApiV1LotsLotIdLogsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>>
export type ListLogsApiV1LotsLotIdLogsGetQueryError = HTTPValidationError


export function useListLogsApiV1LotsLotIdLogsGet<TData = Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError = HTTPValidationError>(
 lotId: string,
    params: undefined |  ListLogsApiV1LotsLotIdLogsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>,
          TError,
          Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLogsApiV1LotsLotIdLogsGet<TData = Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError = HTTPValidationError>(
 lotId: string,
    params?: ListLogsApiV1LotsLotIdLogsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>,
          TError,
          Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLogsApiV1LotsLotIdLogsGet<TData = Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError = HTTPValidationError>(
 lotId: string,
    params?: ListLogsApiV1LotsLotIdLogsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Logs
 */

export function useListLogsApiV1LotsLotIdLogsGet<TData = Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError = HTTPValidationError>(
 lotId: string,
    params?: ListLogsApiV1LotsLotIdLogsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLogsApiV1LotsLotIdLogsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListLogsApiV1LotsLotIdLogsGetQueryOptions(lotId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Process Plate
 */
export const processPlateApiV1PlatesPost = (
    plateRequest: PlateRequest,
 signal?: AbortSignal
) => {


      return mutationInstance<EntryResponse | ExitResponse>(
      {url: `/api/v1/plates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: plateRequest, signal
    },
      );
    }



export const getProcessPlateApiV1PlatesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processPlateApiV1PlatesPost>>, TError,{data: PlateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof processPlateApiV1PlatesPost>>, TError,{data: PlateRequest}, TContext> => {

const mutationKey = ['processPlateApiV1PlatesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processPlateApiV1PlatesPost>>, {data: PlateRequest}> = (props) => {
          const {data} = props ?? {};

          return  processPlateApiV1PlatesPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProcessPlateApiV1PlatesPostMutationResult = NonNullable<Awaited<ReturnType<typeof processPlateApiV1PlatesPost>>>
    export type ProcessPlateApiV1PlatesPostMutationBody = PlateRequest
    export type ProcessPlateApiV1PlatesPostMutationError = HTTPValidationError

    /**
 * @summary Process Plate
 */
export const useProcessPlateApiV1PlatesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processPlateApiV1PlatesPost>>, TError,{data: PlateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof processPlateApiV1PlatesPost>>,
        TError,
        {data: PlateRequest},
        TContext
      > => {
      return useMutation(getProcessPlateApiV1PlatesPostMutationOptions(options), queryClient);
    }
